### ISSUE TITLE
ToDo-list v1.0.0-rc.1 -> v1.0.0

### ISSUE THREAD

**Issue by prisae** [emsig/emg3d#208]
Another TODO-list; from the released `emg3d v1.0.0-rc.2` to `emg3d v1.0.0`:

- [x] Documentation
  - [x] About section (describe also logo)
  - [x] Describe File Format
  - [x] Describe Saving/Loading (in getting started)
  - [x] Example using all source and receiver types (in getting started)
  - [x] Improve development section (including solve-optimization; contributing)
  - [x] Rename: `user_guide`->`manual`; `api_reference`->`api`, `development`->`dev` for shorter links
  - [x] Show source code button
  - [x] ~`>>>` vs `In [1]` (see, e.g., NumPy)~
  - [x] Add `solve` example/benchmark to dev-section
- [x] Testing
  - [x] New version of `discretize`
  - [x] Benchmarks
- [x] Gallery
  - [x] Finish (8 missing)
  - [x] Use `pooch` to fetch data; move data out to own repo.
  - [x] Build automatically on GHA, ~store within emg3d, push artefacts to RTD~ (onto wishlist)
- [x] New logos / favicons (emg3d/empymod/EMSiG)
----
- [x] emsig.xyz
  - [x] Sphinx
  - [x] About section (describe also logo)
  - [x] CNAME's (github.io and rtfd.io)
- [ ] empymod
  - [ ] Update theme & README
  - [ ] About section (describe also logo)
  - [ ] v3.0 / coordinate system (?)

**Comment by prisae** [comment]
Ready for v1 - will treat empymod afterwards.
